// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Web configuration - This is where we put our Firebase credentials
  // These credentials connect our Flutter app to the Firebase project
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAulqyCN7THqTplcgq7H25TE5uMZy4-sZc',
    appId: '1:534476814872:web:209abe6ae336400f87616d',
    messagingSenderId: '534476814872',
    projectId: 'cis-4030-hw',
    authDomain: 'cis-4030-hw.firebaseapp.com',
    storageBucket: 'cis-4030-hw.firebasestorage.app',
    measurementId: 'G-6YW4YMLR5S',
  );

  // Android configuration - Uses the same project
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAulqyCN7THqTplcgq7H25TE5uMZy4-sZc',
    appId: '1:534476814872:android:209abe6ae336400f87616d',
    messagingSenderId: '534476814872',
    projectId: 'cis-4030-hw',
    authDomain: 'cis-4030-hw.firebaseapp.com',
    storageBucket: 'cis-4030-hw.firebasestorage.app',
  );

  // iOS configuration - Uses the same project
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAulqyCN7THqTplcgq7H25TE5uMZy4-sZc',
    appId: '1:534476814872:ios:209abe6ae336400f87616d',
    messagingSenderId: '534476814872',
    projectId: 'cis-4030-hw',
    authDomain: 'cis-4030-hw.firebaseapp.com',
    storageBucket: 'cis-4030-hw.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterWebApp',
  );

  // macOS configuration - Uses the same project
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAulqyCN7THqTplcgq7H25TE5uMZy4-sZc',
    appId: '1:534476814872:macos:209abe6ae336400f87616d',
    messagingSenderId: '534476814872',
    projectId: 'cis-4030-hw',
    authDomain: 'cis-4030-hw.firebaseapp.com',
    storageBucket: 'cis-4030-hw.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterWebApp',
  );

  // Windows configuration - Uses the same project
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAulqyCN7THqTplcgq7H25TE5uMZy4-sZc',
    appId: '1:534476814872:web:209abe6ae336400f87616d',
    messagingSenderId: '534476814872',
    projectId: 'cis-4030-hw',
    authDomain: 'cis-4030-hw.firebaseapp.com',
    storageBucket: 'cis-4030-hw.firebasestorage.app',
    measurementId: 'G-6YW4YMLR5S',
  );
}
